frontend:
  phases:
    preBuild:
      commands:
        - wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.3-stable.tar.xz # Download Flutter (replace with latest version URL)
        - tar xf flutter_linux_*.tar.xz # Extract the downloaded archive
        - export PATH="$PATH:`pwd`/flutter/bin" # Add Flutter to PATH
        - flutter doctor -v # Verify installation
        - flutter pub get # Install dependencies (if your project has any)
    build:
      commands:
        - flutter build web --release  # Compila la app para web (modo release)
  artifacts:
    baseDirectory: build/web
    files:
      - '**/*'
  cache:
    paths:
      - .dart_tool
      - .flutter-plugins
      - .pub-cache
      - build

name: frontend_app9c
description: A Flutter app to manage vehicles using API
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  bloc: ^8.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
